graph BT
  amfcfg[(amfcfg.yaml)] -- load --> AMF(AMF)
  ausfcfg[(ausfcfg.yaml)] -- load --> AUSF(AUSF)
  n3iwfcfg[(n3iwfcfg.yaml)] -- load --> N3IWF(N3IWF)
  nrfcfg[(nrfcfg.yaml)] -- load --> NRF(NRF)
  nssfcfg[(nssfcfg.yaml)] -- load --> NSSF(NSSF)
  pcfcfg[(pcfcfg.yaml)] -- load --> PCF(PCF)
